-- ABA staging: authoritative initial schema.
-- Applied remotely as migration `initial_staging_schema`.

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;
revoke create on schema public from public, anon, authenticated;
grant usage on schema public to anon, authenticated;

create table public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 120),
  status text not null default 'active' check (status in ('active', 'archived')),
  test_run_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.memberships (
  organization_id uuid not null references public.organizations(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete restrict,
  role text not null check (role in ('admin', 'clinician', 'viewer')),
  test_run_id uuid,
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id)
);

create index memberships_user_organization_idx
  on public.memberships (user_id, organization_id);

create table public.clients (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete restrict,
  clinical_id text not null check (char_length(btrim(clinical_id)) between 1 and 64),
  initials text not null check (char_length(btrim(initials)) between 1 and 12),
  primary_language text not null check (char_length(btrim(primary_language)) between 1 and 32),
  birth_date date not null check (birth_date <= current_date),
  living_arrangement text check (living_arrangement is null or char_length(btrim(living_arrangement)) between 1 and 500),
  status text not null default 'active' check (status in ('active', 'archived')),
  test_run_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint clients_organization_clinical_id_key unique (organization_id, clinical_id)
);

create index clients_organization_status_idx
  on public.clients (organization_id, status);

create table public.guardians (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete restrict,
  initials text not null check (char_length(btrim(initials)) between 1 and 12),
  position integer not null check (position >= 0),
  test_run_id uuid,
  created_at timestamptz not null default now(),
  unique (client_id, position)
);

create index guardians_client_idx on public.guardians (client_id);

create table public.siblings (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.clients(id) on delete restrict,
  initials text not null check (char_length(btrim(initials)) between 1 and 12),
  birth_date date check (birth_date is null or birth_date <= current_date),
  position integer not null check (position >= 0),
  test_run_id uuid,
  created_at timestamptz not null default now(),
  unique (client_id, position)
);

create index siblings_client_idx on public.siblings (client_id);

create table public.audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  actor_user_id uuid,
  entity_type text not null check (entity_type in ('client')),
  entity_id uuid not null,
  action text not null check (action in ('created', 'updated', 'archived')),
  test_run_id uuid,
  created_at timestamptz not null default now()
);

create index audit_events_organization_created_idx
  on public.audit_events (organization_id, created_at desc);
create index audit_events_entity_idx
  on public.audit_events (entity_type, entity_id);

alter table public.organizations enable row level security;
alter table public.memberships enable row level security;
alter table public.clients enable row level security;
alter table public.guardians enable row level security;
alter table public.siblings enable row level security;
alter table public.audit_events enable row level security;

create policy organizations_select_member
on public.organizations
for select
to authenticated
using (
  exists (
    select 1
    from public.memberships m
    where m.organization_id = organizations.id
      and m.user_id = (select auth.uid())
  )
);

create policy memberships_select_self
on public.memberships
for select
to authenticated
using (user_id = (select auth.uid()));

create policy clients_select_member
on public.clients
for select
to authenticated
using (
  exists (
    select 1
    from public.memberships m
    where m.organization_id = clients.organization_id
      and m.user_id = (select auth.uid())
  )
);

create policy clients_insert_writer
on public.clients
for insert
to authenticated
with check (
  exists (
    select 1
    from public.memberships m
    where m.organization_id = clients.organization_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
);

create policy clients_update_writer
on public.clients
for update
to authenticated
using (
  exists (
    select 1
    from public.memberships m
    where m.organization_id = clients.organization_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
)
with check (
  exists (
    select 1
    from public.memberships m
    where m.organization_id = clients.organization_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
);

create policy guardians_select_member
on public.guardians
for select
to authenticated
using (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = guardians.client_id
      and m.user_id = (select auth.uid())
  )
);

create policy guardians_insert_writer
on public.guardians
for insert
to authenticated
with check (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = guardians.client_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
);

create policy guardians_update_writer
on public.guardians
for update
to authenticated
using (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = guardians.client_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
)
with check (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = guardians.client_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
);

create policy siblings_select_member
on public.siblings
for select
to authenticated
using (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = siblings.client_id
      and m.user_id = (select auth.uid())
  )
);

create policy siblings_insert_writer
on public.siblings
for insert
to authenticated
with check (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = siblings.client_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
);

create policy siblings_update_writer
on public.siblings
for update
to authenticated
using (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = siblings.client_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
)
with check (
  exists (
    select 1
    from public.clients c
    join public.memberships m on m.organization_id = c.organization_id
    where c.id = siblings.client_id
      and m.user_id = (select auth.uid())
      and m.role in ('admin', 'clinician')
  )
);

create function private.prevent_client_organization_reassignment()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if new.organization_id is distinct from old.organization_id then
    raise exception using
      errcode = '42501',
      message = 'client_organization_is_immutable';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

revoke all on function private.prevent_client_organization_reassignment() from public, anon, authenticated;

create trigger clients_prevent_organization_reassignment
before update on public.clients
for each row execute function private.prevent_client_organization_reassignment();

create function private.audit_client_insert()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.audit_events (
    organization_id,
    actor_user_id,
    entity_type,
    entity_id,
    action,
    test_run_id
  ) values (
    new.organization_id,
    (select auth.uid()),
    'client',
    new.id,
    'created',
    new.test_run_id
  );
  return new;
end;
$$;

revoke all on function private.audit_client_insert() from public, anon, authenticated;

create trigger clients_audit_insert
after insert on public.clients
for each row execute function private.audit_client_insert();

create function public.create_client(
  p_clinical_id text,
  p_initials text,
  p_primary_language text,
  p_birth_date date,
  p_living_arrangement text default null,
  p_guardians jsonb default '[]'::jsonb,
  p_siblings jsonb default '[]'::jsonb,
  p_test_run_id uuid default null
)
returns public.clients
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_organization_id uuid;
  v_membership_count integer;
  v_client public.clients;
begin
  select count(*), min(m.organization_id::text)::uuid
    into v_membership_count, v_organization_id
  from public.memberships m
  where m.user_id = (select auth.uid())
    and m.role in ('admin', 'clinician');

  if v_membership_count <> 1 then
    raise exception using
      errcode = '42501',
      message = 'single_writable_membership_required';
  end if;

  if jsonb_typeof(p_guardians) <> 'array' or jsonb_typeof(p_siblings) <> 'array' then
    raise exception using
      errcode = '22023',
      message = 'family_payload_must_be_arrays';
  end if;

  insert into public.clients (
    organization_id,
    clinical_id,
    initials,
    primary_language,
    birth_date,
    living_arrangement,
    test_run_id
  ) values (
    v_organization_id,
    btrim(p_clinical_id),
    upper(btrim(p_initials)),
    btrim(p_primary_language),
    p_birth_date,
    nullif(btrim(p_living_arrangement), ''),
    p_test_run_id
  )
  returning * into v_client;

  insert into public.guardians (client_id, initials, position, test_run_id)
  select
    v_client.id,
    upper(btrim(item.value ->> 'initials')),
    item.ordinality - 1,
    p_test_run_id
  from jsonb_array_elements(p_guardians) with ordinality as item(value, ordinality);

  insert into public.siblings (client_id, initials, birth_date, position, test_run_id)
  select
    v_client.id,
    upper(btrim(item.value ->> 'initials')),
    nullif(item.value ->> 'birth_date', '')::date,
    item.ordinality - 1,
    p_test_run_id
  from jsonb_array_elements(p_siblings) with ordinality as item(value, ordinality);

  return v_client;
end;
$$;

revoke all on table public.organizations from public, anon, authenticated;
revoke all on table public.memberships from public, anon, authenticated;
revoke all on table public.clients from public, anon, authenticated;
revoke all on table public.guardians from public, anon, authenticated;
revoke all on table public.siblings from public, anon, authenticated;
revoke all on table public.audit_events from public, anon, authenticated;

grant select on table public.organizations to authenticated;
grant select on table public.memberships to authenticated;
grant select, insert, update on table public.clients to authenticated;
grant select, insert, update on table public.guardians to authenticated;
grant select, insert, update on table public.siblings to authenticated;

revoke all on function public.create_client(text, text, text, date, text, jsonb, jsonb, uuid)
  from public, anon, authenticated;
grant execute on function public.create_client(text, text, text, date, text, jsonb, jsonb, uuid)
  to authenticated;
