-- S-ABA-01: dedicated append-only audit ledger without altering historical clinical constraints.
create table public.student_access_audit_events (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete restrict,
  actor_user_id uuid references auth.users(id) on delete restrict,
  client_id uuid not null references public.clients(id) on delete restrict,
  entity_type text not null check (entity_type in ('student_assignment', 'authorization_request', 'authorization_decision')),
  entity_id uuid not null,
  action text not null check (action in ('assigned', 'unassigned', 'requested', 'approved', 'denied', 'revoked')),
  created_at timestamptz not null default now(),
  test_run_id uuid
);

create index student_access_audit_client_idx
  on public.student_access_audit_events (client_id, created_at desc);
create index student_access_audit_actor_idx
  on public.student_access_audit_events (actor_user_id, created_at desc);
alter table public.student_access_audit_events enable row level security;
revoke all on table public.student_access_audit_events from public, anon, authenticated;

create function private.audit_student_access_event(
  p_organization_id uuid,
  p_client_id uuid,
  p_entity_type text,
  p_entity_id uuid,
  p_action text,
  p_test_run_id uuid
)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.student_access_audit_events (
    organization_id, actor_user_id, client_id, entity_type, entity_id, action, test_run_id
  ) values (
    p_organization_id, (select auth.uid()), p_client_id,
    p_entity_type, p_entity_id, p_action, p_test_run_id
  );
$$;

revoke all on function private.audit_student_access_event(uuid, uuid, text, uuid, text, uuid)
  from public, anon, authenticated;

create or replace function public.request_student_authorization(
  p_client_id uuid, p_resource_type text, p_actions text[], p_reason text,
  p_test_run_id uuid default null
)
returns public.student_authorization_requests
language plpgsql security definer set search_path = ''
as $$
declare
  v_organization_id uuid;
  v_request public.student_authorization_requests;
  v_actions text[];
begin
  if (select auth.uid()) is null or (select private.student_assignment_role(p_client_id)) <> 'coordinator' then
    raise exception using errcode = '42501', message = 'coordinator_assignment_required';
  end if;
  if p_resource_type not in ('student', 'program', 'record_config', 'chart') then
    raise exception using errcode = '22023', message = 'invalid_resource_type';
  end if;
  select array_agg(distinct action order by action) into v_actions from unnest(p_actions) action;
  if cardinality(v_actions) = 0 or exists (
    select 1 from unnest(v_actions) action
    where action not in ('student.edit', 'program.edit', 'record_config.create', 'record_config.edit', 'chart.configure')
  ) then raise exception using errcode = '22023', message = 'invalid_requested_actions'; end if;
  select c.organization_id into strict v_organization_id from public.clients c where c.id = p_client_id;
  select * into v_request from public.student_authorization_requests r
  where r.client_id = p_client_id and r.requester_user_id = (select auth.uid())
    and r.resource_type = p_resource_type and r.requested_actions = v_actions and r.status = 'pending'
  limit 1;
  if found then return v_request; end if;
  insert into public.student_authorization_requests (
    organization_id, client_id, requester_user_id, resource_type, requested_actions, reason, test_run_id
  ) values (
    v_organization_id, p_client_id, (select auth.uid()), p_resource_type, v_actions, btrim(p_reason), p_test_run_id
  ) returning * into v_request;
  perform private.audit_student_access_event(v_organization_id, p_client_id, 'authorization_request', v_request.id, 'requested', p_test_run_id);
  return v_request;
end;
$$;

create or replace function public.decide_student_authorization(
  p_request_id uuid, p_decision text, p_expires_at timestamptz default null,
  p_test_run_id uuid default null
)
returns public.student_authorization_decisions
language plpgsql security definer set search_path = ''
as $$
declare
  v_request public.student_authorization_requests;
  v_decision public.student_authorization_decisions;
begin
  select * into strict v_request from public.student_authorization_requests r
  where r.id = p_request_id for update;
  if not (select private.is_primary_student_supervisor(v_request.client_id)) then
    raise exception using errcode = '42501', message = 'primary_supervisor_required';
  end if;
  if v_request.status <> 'pending' then
    raise exception using errcode = '40001', message = 'authorization_state_changed';
  end if;
  if p_decision not in ('approved', 'denied') then
    raise exception using errcode = '22023', message = 'invalid_authorization_decision';
  end if;
  if p_decision = 'approved' and (
    p_expires_at is null or p_expires_at <= now() or p_expires_at > now() + interval '90 days'
  ) then raise exception using errcode = '22023', message = 'authorization_expiry_out_of_range'; end if;
  insert into public.student_authorization_decisions (
    organization_id, client_id, request_id, decider_user_id, decision, granted_actions, expires_at, test_run_id
  ) values (
    v_request.organization_id, v_request.client_id, v_request.id, (select auth.uid()), p_decision,
    case when p_decision = 'approved' then v_request.requested_actions else '{}'::text[] end,
    case when p_decision = 'approved' then p_expires_at else null end, p_test_run_id
  ) returning * into v_decision;
  update public.student_authorization_requests set status = p_decision, resolved_at = now()
  where id = v_request.id;
  perform private.audit_student_access_event(v_request.organization_id, v_request.client_id, 'authorization_decision', v_decision.id, p_decision, p_test_run_id);
  return v_decision;
end;
$$;

create or replace function public.revoke_student_authorization(
  p_decision_id uuid, p_test_run_id uuid default null
)
returns public.student_authorization_decisions
language plpgsql security definer set search_path = ''
as $$
declare
  v_prior public.student_authorization_decisions;
  v_revocation public.student_authorization_decisions;
begin
  select * into strict v_prior from public.student_authorization_decisions d
  where d.id = p_decision_id and d.decision = 'approved';
  if not (select private.is_primary_student_supervisor(v_prior.client_id)) then
    raise exception using errcode = '42501', message = 'primary_supervisor_required';
  end if;
  if exists (select 1 from public.student_authorization_decisions d where d.supersedes_decision_id = v_prior.id and d.decision = 'revoked') then
    raise exception using errcode = '40001', message = 'authorization_state_changed';
  end if;
  insert into public.student_authorization_decisions (
    organization_id, client_id, request_id, decider_user_id, decision,
    granted_actions, supersedes_decision_id, test_run_id
  ) values (
    v_prior.organization_id, v_prior.client_id, v_prior.request_id,
    (select auth.uid()), 'revoked', '{}'::text[], v_prior.id, p_test_run_id
  ) returning * into v_revocation;
  perform private.audit_student_access_event(v_prior.organization_id, v_prior.client_id, 'authorization_decision', v_revocation.id, 'revoked', p_test_run_id);
  return v_revocation;
end;
$$;

create or replace function public.set_student_assignment(
  p_client_id uuid, p_user_id uuid, p_role text, p_status text default 'active',
  p_test_run_id uuid default null
)
returns public.student_assignments
language plpgsql security definer set search_path = ''
as $$
declare
  v_organization_id uuid;
  v_assignment public.student_assignments;
begin
  if not (select private.is_primary_student_supervisor(p_client_id)) then
    raise exception using errcode = '42501', message = 'primary_supervisor_required';
  end if;
  if p_user_id = (select auth.uid()) then
    raise exception using errcode = '22023', message = 'self_assignment_change_not_allowed';
  end if;
  if p_role not in ('supervisor', 'coordinator', 'therapist', 'family') or p_status not in ('active', 'inactive') then
    raise exception using errcode = '22023', message = 'invalid_assignment';
  end if;
  select c.organization_id into strict v_organization_id from public.clients c where c.id = p_client_id;
  if not exists (select 1 from public.memberships m where m.organization_id = v_organization_id and m.user_id = p_user_id and m.status = 'active') then
    raise exception using errcode = '42501', message = 'active_membership_required';
  end if;
  select * into v_assignment from public.student_assignments sa
  where sa.client_id = p_client_id and sa.user_id = p_user_id and sa.status = 'active' for update;
  if found then
    update public.student_assignments
    set role = p_role, status = p_status,
        ended_at = case when p_status = 'inactive' then now() else null end,
        test_run_id = coalesce(p_test_run_id, test_run_id)
    where id = v_assignment.id returning * into v_assignment;
  elsif p_status = 'active' then
    insert into public.student_assignments (
      organization_id, client_id, user_id, role, is_primary, created_by, test_run_id
    ) values (
      v_organization_id, p_client_id, p_user_id, p_role, false, (select auth.uid()), p_test_run_id
    ) returning * into v_assignment;
  else raise exception using errcode = '22023', message = 'active_assignment_not_found';
  end if;
  perform private.audit_student_access_event(
    v_organization_id, p_client_id, 'student_assignment', v_assignment.id,
    case when p_status = 'active' then 'assigned' else 'unassigned' end, p_test_run_id
  );
  return v_assignment;
end;
$$;

